### ISSUE TITLE
fix(settings): ensure settings sync between multi replicas

### ISSUE THREAD

**Issue by OrenZhang** [open-webui/open-webui#10365]
# Bug Report

## Installation Method

Pod in K8S Cluster

## Environment

- **Open WebUI Version:** v0.5.14
- **Operating System:** MacOS 15
- **Browser:** Edge 133.0

## Description

**Bug Summary:**

When using open-webui for multi-replica deployment, configuration changes do not take effect across different replicas, possibly due to the settings being loaded into memory. For example, after enabling internet search, querying `/api/v1/retrieval/config` occasionally still shows `web.search.enable` as false. The issue is resolved after restarting all the Pods.

## Reproduction Details

**Steps to Reproduce:**

- Scale the open-webui deployment to 2 or more Pods.
- Change some configuration settings and save them.
- Use the API (e.g., /api/v1/retrieval/config) to check if the settings have been applied.
- Refresh and repeat the API call multiple times to ensure requests are routed to different Pods.

**Comment by tjbck** [comment]
Taking a look!

**Comment by a517363523** [comment]
Has it been fixed? I also encountered this problem

**Comment by tkg61** [comment]
> Has it been fixed? I also encountered this problem

Not yet, still have it in 5.18

**Comment by tjbck** [comment]
Allocating more resources into resolving this issue, aiming for 0.5.21

**Comment by tjbck** [comment]
Addressed with d40e69646823f31711f6ad6c269456d2435c0d01, Proper redis configuration is required.

**Comment by tkg61** [comment]
Still having issues with this in 0.6.0 with redis configured. Settings are not synced between instances. i can just refresh the page and see different banners appear between the instances

**Comment by tkg61** [comment]
@tjbck Still having issues in .6.2 with a fresh install via the helm chart. Not sure what else to try at the moment. Let me know if i should open up another ticket

![Image](https://github.com/user-attachments/assets/cc3241db-2aa2-4a97-8fb3-d817c49c40d4)

![Image](https://github.com/user-attachments/assets/2a66378f-8463-4ab6-8a27-b555e97fef6a)

**Comment by sFritsch09** [comment]
> @tjbck Still having issues in .6.2 with a fresh install via the helm chart. Not sure what else to try at the moment. Let me know if i should open up another ticket
> 
> ![Image](https://github.com/user-attachments/assets/cc3241db-2aa2-4a97-8fb3-d817c49c40d4)
> 
> ![Image](https://github.com/user-attachments/assets/2a66378f-8463-4ab6-8a27-b555e97fef6a)

Can you share a minimal values file without exposing personals to check if have websockets turned on in your ingress for example

**Comment by tkg61** [comment]
> [@tkg61](https://github.com/tkg61) did you also set the REDIS_URL environment variable or only the WEBHOOK_REDIS_URL ?
> 
> make sure to configure both, then it should work afaik

Ah, that might be it, i don't see that in the configured envs. Thanks for the clarification. Will make a ticket in the helm repo to update as well.

**Comment by Classic298** [comment]
Wonderful! Enjoy

**Comment by Classic298** [comment]
PR to improve docs to inform users that all these variables need to be set: https://github.com/open-webui/docs/pull/481
