### ISSUE TITLE
issue: previous prompt is cached when new chat starts

### ISSUE THREAD

**Issue by akras14** [open-webui/open-webui#13753]
### Check Existing Issues

- [x] I have searched the existing issues and discussions.
- [x] I am using the latest version of Open WebUI.

### Installation Method

Pip Install

### Open WebUI Version

v0.6.8

### Operating System

macOS

### Browser (if applicable)

Chrome

### Confirmation

- [x] I have read and followed all instructions in `README.md`.
- [x] I am using the latest version of **both** Open WebUI and Ollama.
- [x] I have included the browser console logs.
- [x] I have included the Docker container logs.
- [x] I have listed steps to reproduce the bug in detail.

### Expected Behavior

1. Refresh the URL, i.e. http://localhost:8080/?temporary-chat=true 
2. Expect to see clear prompt to start a new chat

### Actual Behavior

1. Refresh the URL, i.e. http://localhost:8080/?temporary-chat=true 
2. A prompt from previous chat is cached and displayed in the UI

### Steps to Reproduce

1. Refresh the URL, i.e. http://localhost:8080/?temporary-chat=true 
2. A prompt from previous chat is cached and displayed in the UI

### Logs & Screenshots

![Image](https://github.com/user-attachments/assets/e850d332-82d3-4046-b8e8-861a0b47160f)

**Comment by tjbck** [comment]
Addressed with ba69c751ca0ec489604bedfa4041fc71a49e304c in dev

**Comment by kautsig** [comment]
@tjbck I fear [ba69c](https://github.com/open-webui/open-webui/commit/ba69c751ca0ec489604bedfa4041fc71a49e304c) does not address the issue.

I can still reproduce it in `v0.6.13`.

If understand the code change correctly, the attempted fix prevents the input field to be prefilled in a temporary chat session. ~This is, however, not the issue.~

The data is still *written* to local storage in a temporary chat [here](https://github.com/open-webui/open-webui/blob/main/src/lib/components/chat/Chat.svelte#L2095) unconditionally. The read happens in a non-temporary chat and restores the previously written "temporary" value from local storage.

Edit: I just noticed that the bug describes the a temporary chat only  scenario. I can open a new issue for this, if needed.
