### ISSUE TITLE
issue: task models error when base64 text content is present (images)

### ISSUE THREAD

**Issue by almajo** [open-webui/open-webui#13834]
### Check Existing Issues

- [x] I have searched the existing issues and discussions.
- [x] I am using the latest version of Open WebUI.

### Installation Method

Git Clone

### Open WebUI Version

v0.6.9

### Operating System

linux

### Confirmation

- [x] I have read and followed all instructions in `README.md`.
- [x] I am using the latest version of **both** Open WebUI and Ollama.
- [x] I have included the browser console logs.
- [x] I have included the Docker container logs.
- [x] I have listed steps to reproduce the bug in detail.

### Expected Behavior

Task models like title and tag generation should work without images or other base64 content for quick and cheap responses. 

### Actual Behavior

As embedded images are simply text, they use a lot of tokens and thereby surpass context lengths which leads to chats being called "New Chat".

### Steps to Reproduce

1. Create a large image with any model so that it is present in the chat (e.g. the gpt-image-1 function)

### Logs & Screenshots

<img width="380" alt="Image" src="https://github.com/user-attachments/assets/5839cbc6-699a-4836-99ac-41c4fdfa45f5" />

### Additional Information

I already added a fix in the latest release for some use cases but forgot about the embedded image case. This should be an easy add-on in the implementation.

**Comment by tjbck** [comment]
Should be addressed by 528a2cf96a8bef32fd9f8fdc8467908b52895a3a, testing wanted here!

**Comment by almajo** [comment]
Hey, as far as I see, this doesn't fix the issue.

The use case I described is especially important for Functions which create images and show them to the user via markdown. Hereby, they simply emit the picture as a string, hence the content would be as string in `message['content']`.

A fix would be 

```python
if isinstance(content, str):
    patterns = [r"<details\b[^>]*>.*?<\/details>", "r"!\[.*?\]\(data:image\/[a-zA-Z]+;base64,[A-Za-z0-9+/=]+\)"]
    for p in patterns:
      content = re.sub(
          p,
          "",
          content,
          flags=re.S | re.I,
      ).strip()
```

The base64 pattern should be verified
