### ISSUE TITLE
issue: Can't search knowlege by any term like we can search for Models in Workspace view

### ISSUE THREAD

**Issue by le-patenteux** [open-webui/open-webui#16544]
### Check Existing Issues

- [x] I have searched the existing issues and discussions.
- [x] I am using the latest version of Open WebUI.

### Installation Method

Docker

### Open WebUI Version

0.6.21

### Ollama Version (if applicable)

N/A

### Operating System

Ubuntu server 24.04

### Browser (if applicable)

Brave, Firefox

### Confirmation

- [x] I have read and followed all instructions in `README.md`.
- [x] I am using the latest version of **both** Open WebUI and Ollama.
- [x] I have included the browser console logs.
- [x] I have included the Docker container logs.
- [x] I have **provided every relevant configuration, setting, and environment variable used in my setup.**
- [x] I have clearly **listed every relevant configuration, custom setting, environment variable, and command-line option that influences my setup** (such as Docker Compose overrides, .env values, browser settings, authentication configurations, etc).
- [x] I have documented **step-by-step reproduction instructions that are precise, sequential, and leave nothing to interpretation**. My steps:
- Start with the initial platform/version/OS and dependencies used,
- Specify exact install/launch/configure commands,
- List URLs visited, user input (incl. example values/emails/passwords if needed),
- Describe all options and toggles enabled or changed,
- Include any files or environmental changes,
- Identify the expected and actual result at each stage,
- Ensure any reasonably skilled user can follow and hit the same issue.

### Expected Behavior

When searching for Knowlegbases in the Workspace, I should be able to search using any term, like when searching for models.

<img width="1748" height="520" alt="Image" src="https://github.com/user-attachments/assets/89bb4998-b285-4671-a508-b557b9a8d7ff" />

### Model search: Expected behavior (not the same for Knowlege)
When doing a Model search in the workspace, I can search by any combination of letter that are within the title or description  and this is perfect!

<img width="776" height="375" alt="Image" src="https://github.com/user-attachments/assets/0b729a83-4e65-4765-baa0-cab27f1c35ab" />

### Actual Behavior

When in worskpace view, under "Knowledge", to search for a specific collection, I need to search using the exact terms, starting only by the first letter of the Knowlegebase name

<img width="707" height="218" alt="Image" src="https://github.com/user-attachments/assets/cee79218-0897-4a8d-bd86-f448ab5b4fa3" />

If I search using the first term, starting by the first letter it works

<img width="790" height="254" alt="Image" src="https://github.com/user-attachments/assets/674cebcf-3588-45dc-b17a-5e8cb836a4bf" />

It also does the same with the first term of the description

<img width="859" height="311" alt="Image" src="https://github.com/user-attachments/assets/c134a424-68fe-477f-9b34-6b373e81a59a" />

### Steps to Reproduce

In any recent version of Open-Webui, go to the "Workspace" menu, and in "Knowledge" Search for a term without starting by the exact first letter
You will get no result.

### Logs & Screenshots

See screenshots above.

### Additional Information

With larger Knowledgebases, it makes searching a real issue. You have to remember exactly the name of the collection you created to search for it, which defies the purpose.

Sorry if my english is not perfect, I usually speak French

**Comment by rgaricano** [comment]
Probably is because query is converted to lower case, and it is done to Unicode and in standardized methods, maybe some accents could be lost:
https://github.com/open-webui/open-webui/blob/438e5d966f0f64f9ea3feab22724a5bd96a4127b/src/lib/components/workspace/Models.svelte#L64

Not sure, but using _.toLocaleLowerCase()_ could solve this (or using other string normalization method)

The search use include, then doesn't matter where the string it's, if working correctly it have to search for the string in any place of the name.

**Comment by le-patenteux** [comment]
> Probably is because query is converted to lower case, and it is done to Unicode and in standardized methods, maybe some accents could be lost:
> 
> [open-webui/src/lib/components/workspace/Models.svelte](https://github.com/open-webui/open-webui/blob/438e5d966f0f64f9ea3feab22724a5bd96a4127b/src/lib/components/workspace/Models.svelte#L64)
> 
> Line 64 in [438e5d9](/open-webui/open-webui/commit/438e5d966f0f64f9ea3feab22724a5bd96a4127b)
> 
>  			const lowerQuery = query.toLowerCase(); 
> Not sure, but using _.toLocaleLowerCase()_ could solve this (or using other string normalization method)
> 
> The search use include, then doesn't matter where the string it's, if working correctly it have to search for the string in any place of the name.

It has the same issue with un-accented characters... When searching, it will not search for strings inside the name (it does it correctly for models, not for knowlege) and it hapens on 3 different servers I tried it on.

**Comment by rgaricano** [comment]
Yes, it's true, I was mistaken in thinking that the problem was with models.

**Comment by tjbck** [comment]
Addressed with c134de8799bb78f5c2c84077b464bb9f4f16a21c!

**Comment by le-patenteux** [comment]
> Addressed with [c134de8](https://github.com/open-webui/open-webui/commit/c134de8799bb78f5c2c84077b464bb9f4f16a21c)!

I am no developper, but not sure this adresses the issue directly... It seems more like a precision "score" threshold... 
But that does not fix the issue that it won't search for a string in the middle of the name.
If I write the exact string, but it is in the middle of the name, it is not finding it right now... Will it really fix that?
