### ISSUE TITLE
issue: SCIM endpoints accessible even when not listed in `API_KEY_ALLOWED_ENDPOINTS`

### ISSUE THREAD

**Issue by flefevre** [open-webui/open-webui#19168]
### Check Existing Issues

- [x] I have searched for any existing and/or related issues.
- [x] I have searched for any existing and/or related discussions.
- [x] I have also searched in the CLOSED issues AND CLOSED discussions and found no related items (your issue might already be addressed on the development branch!).
- [x] I am using the latest version of Open WebUI.

### Installation Method

Docker

### Open WebUI Version

v0.6.36

### Operating System

Ubuntu 22.04

### Confirmation

- [x] I have read and followed all instructions in `README.md`.
- [x] I am using the latest version of **both** Open WebUI and Ollama.
- [x] I have included the browser console logs.
- [x] I have included the Docker container logs.
- [x] I have **provided every relevant configuration, setting, and environment variable used in my setup.**
- [x] I have clearly **listed every relevant configuration, custom setting, environment variable, and command-line option that influences my setup** (such as Docker Compose overrides, .env values, browser settings, authentication configurations, etc).
- [x] I have documented **step-by-step reproduction instructions that are precise, sequential, and leave nothing to interpretation**. My steps:
- Start with the initial platform/version/OS and dependencies used,
- Specify exact install/launch/configure commands,
- List URLs visited, user input (incl. example values/emails/passwords if needed),
- Describe all options and toggles enabled or changed,
- Include any files or environmental changes,
- Identify the expected and actual result at each stage,
- Ensure any reasonably skilled user can follow and hit the same issue.

### Expected Behavior

After configuring `API_KEY_ALLOWED_ENDPOINTS` to restrict access to specific API endpoints, I noticed that the SCIM endpoints (`/api/v1/scim/v2/`) remain accessible even though they are **not included** in the allowed list.

SCIM endpoints should **not** be accessible unless explicitly listed in `API_KEY_ALLOWED_ENDPOINTS`.

### Actual Behavior

SCIM endpoints are accessible with a valid `SCIM_TOKEN` even when not included in `API_KEY_ALLOWED_ENDPOINTS`.

### Steps to Reproduce

1. Start Open WebUI.
2. Try accessing a SCIM endpoint using `curl` and the SCIM token:

```bash - curl -H "Authorization: Bearer $SCIM_TOKEN" https://<your-instance>/api/v1/scim/v2/Users
````

3. The request succeeds and returns data, even though `/api/v1/scim/v2/` is not part of `API_KEY_ALLOWED_ENDPOINTS`.

### Logs & Screenshots

no log

### Additional Information

This behavior could allow unintended access to SCIM resources when endpoint restrictions are expected to be enforced globally.

**Comment by tjbck** [comment]
Should be addressed in dev with b160eef7ebd625ff9c7291f6edce9493ba58d09f, testing wanted here!

cc @silentoplayz

**Comment by silentoplayz** [comment]
> Should be addressed in dev with [b160eef](https://github.com/open-webui/open-webui/commit/b160eef7ebd625ff9c7291f6edce9493ba58d09f), testing wanted here!
> 
> cc [@silentoplayz](https://github.com/silentoplayz)

Re: Check messages on Discord. I believe the issue is confirmed by me to still exist.

**Comment by tjbck** [comment]
Addressed in dev.

**Comment by flefevre** [comment]
Tanks you for the patch.
