### ISSUE TITLE
bug: OpenWebUI Bug Report: User Group and Model Image Display Issues

### ISSUE THREAD

**Issue by jotaperez3** [open-webui/open-webui#19885]
### Check Existing Issues

- [x] I have searched for any existing and/or related issues.
- [x] I have searched for any existing and/or related discussions.
- [x] I have also searched in the CLOSED issues AND CLOSED discussions and found no related items (your issue might already be addressed on the development branch!).
- [x] I am using the latest version of Open WebUI.

### Installation Method

Git Clone

### Open WebUI Version

0.6.41

### Operating System

Windows

### Confirmation

- [x] I have read and followed all instructions in `README.md`.
- [x] I am using the latest version of **both** Open WebUI and Ollama.
- [x] I have included the browser console logs.
- [x] I have included the Docker container logs.
- [x] I have **provided every relevant configuration, setting, and environment variable used in my setup.**
- [x] I have clearly **listed every relevant configuration, custom setting, environment variable, and command-line option that influences my setup** (such as Docker Compose overrides, .env values, browser settings, authentication configurations, etc).
- [x] I have documented **step-by-step reproduction instructions that are precise, sequential, and leave nothing to interpretation**. My steps:
- Start with the initial platform/version/OS and dependencies used,
- Specify exact install/launch/configure commands,
- List URLs visited, user input (incl. example values/emails/passwords if needed),
- Describe all options and toggles enabled or changed,
- Include any files or environmental changes,
- Identify the expected and actual result at each stage,
- Ensure any reasonably skilled user can follow and hit the same issue.

### Expected Behavior

1. **User Group Selection Bug:**
When adding users to a group in the "Edit User Group" section, users should be able to select checkboxes on any page within the "Users" list. The interface should retain the user's current page selection after checking a user.
 
2. **Model Image Display Bug:**
Upon selecting a user on any page other than the first, the interface unexpectedly redirects the user back to the first page of the user list. This disrupts the selection process.

### Actual Behavior

1. **User Group Selection Bug:**
Upon selecting a user on any page other than the first, the interface unexpectedly redirects the user back to the first page of the user list. This disrupts the selection process.
 
2. **Model Image Display Bug:**
Although the new image appears to be saved in the model settings, the chat window continues to display the default OpenWebUI icon. The custom image change is not reflected.

### Steps to Reproduce

1. **User Group Selection Bug:**
- Navigate to the "Edit User Group" section.
- Go to the "Users" list.
- Navigate to a page beyond the first page (e.g., page 2, 3, etc.).
- Locate a user you wish to add.
- Click the checkbox next to the user's name.
- Observe the page reload and return to the first page, losing your place.

2. **Model Image Display Bug:**
- Navigate to the model settings.
- Select a model.
- Change the image associated with the model (e.g., upload a new image or select a different one).
- Save the settings.
- Navigate to the chat window and select the model.
- Observe that the new image does not appear; the default OpenWebUI icon is still displayed.

### Logs & Screenshots

N/A

**Comment by tjbck** [comment]
@silentoplayz confirmation wanted here

**Comment by silentoplayz** [comment]
> User Group Selection Bug:
Upon selecting a user on any page other than the first, the interface unexpectedly redirects the user back to the first page of the user list. This disrupts the selection process.

I can confirm this is an issue, yes. The user expects to stay on the page they were viewing, even if a checkbox is clicked next to a user, rather than being unexpectedly taken back to the first page of users to select from in the `Edit User Group` modal.

> Model Image Display Bug:
Although the new image appears to be saved in the model settings, the chat window continues to display the default Open WebUI icon. The custom image change is not reflected.

The model's avatar image is not being updated automatically in the **list of models via the `Models` page of the admin settings**. It is a **cache** issue. I believe the admin panel models list would benefit from cache busting (Cache-control headers to prevent stale cached images), particularly for the model avatar images.

<img width="2301" height="1285" alt="Image" src="https://github.com/user-attachments/assets/9bb182b7-d5e8-4363-9ed4-dc4645a1f7c5" />

Editing the model after saving an avatar image for it reveals an avatar image is still set, despite it not being visible in the list of models via the `Models` page of the admin settings. The default model avatar is used here still instead.

<img width="2300" height="1073" alt="Image" src="https://github.com/user-attachments/assets/419da4a9-6b49-43d1-ae09-26186b008cb2" />

The model's avatar image **IS** being updated automatically **in the model drop-down selector**.

<img width="552" height="237" alt="Image" src="https://github.com/user-attachments/assets/85da8df8-6660-422c-a4ac-01f4fabc85ba" />

**Comment by Classic298** [comment]
@silentoplayz freebie?

**Comment by silentoplayz** [comment]
> [@silentoplayz](https://github.com/silentoplayz) freebie?

Thoughts on adding cache busting (Cache-control headers to prevent stale cached images), particularly for the model avatar images in the models list here?

**Comment by silentoplayz** [comment]
Should be solved on the `dev` branch!

**Comment by TMKI5** [comment]
The model image display bug is still at least somewhat an issue for Arena Models. I cannot update the avatar for those successfully.
