### ISSUE TITLE
SearXNG web search with openwebui,got this error Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by KnoxCheung** [open-webui/open-webui#2797]
Expecting value: line 1 column 1 (char 0)

![スクリーンショット 2024-06-04 午前11 08 04](https://github.com/open-webui/open-webui/assets/162684964/790efe01-bcfd-469b-b374-e33ec94dff7f)
![スクリーンショット 2024-06-04 午前11 05 56](https://github.com/open-webui/open-webui/assets/162684964/2cf3b876-4744-42e7-9249-2618e6c506b4)

both run on docker
 
port 3001 for openwebui

port 8080 for searxng

<img width="1223" alt="スクリーンショット 2024-06-04 午前11 09 40" src="https://github.com/open-webui/open-webui/assets/162684964/940267af-e9e7-4c81-9661-0d95dfd389ed">

I am a novice of programming ,sorry to bother you guys. Thanks for your help

**Comment by justinh-rahb** [comment]
We've pushed some updates to fix a bad PR merge, re-pull and re-run your container.

**Comment by tjbck** [comment]
Closing this issue, Let us know if the issue persists!

**Comment by KnoxCheung** [comment]
I hv update to 0.2.3, but still the same error
ollama is also the newest version

**Comment by tjbck** [comment]
Try 0.2.4, and let us know if the issue persists!

**Comment by KnoxCheung** [comment]
Sorry to bother you guys,still the same error, i hv updated to 0.2.4,is there something need to be configure in openwebui or searxng?Searxng works fine in localhost:8080.

**Comment by tjbck** [comment]
If both environments are on docker, I don't think the url should be `localhost`. Try `host.docker.internal`.

**Comment by KnoxCheung** [comment]
> If both environments are on docker, I don't think the url should be `localhost`. Try `host.docker.internal`.

It finally works!!! thanks a lot bro.

**Comment by cojarbi** [comment]
Hi guys, having this same issue, im getting that same error with not internet search. localhost for searxng works fine.
open-webui v0.3.1
Ollama 0.1.42

How did you make it work @KnoxCheung

**Comment by KnoxCheung** [comment]
> Hi guys, having this same issue, im getting that same error with not internet search. using searxng localhost for searxng works fine. open-webui v0.3.1 Ollama 0.1.42
> 
> How did you make it work @KnoxCheung
The URL should be host.docker.internal, not localhost (thanks to tjbak's reply)

**Comment by suman-somu** [comment]
![image](https://github.com/open-webui/open-webui/assets/75962762/301f7821-e5b4-4493-8615-c2430223933c)


I'm having this error after changing ```localhost``` to ```host.docker.internal``` 
My versions are - 
![image](https://github.com/open-webui/open-webui/assets/75962762/0ac61970-9041-4101-8f24-93d120f4cd30)

**Comment by silentoplayz** [comment]
> ![image](https://private-user-images.githubusercontent.com/75962762/339329412-301f7821-e5b4-4493-8615-c2430223933c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyODQ3MDIsIm5iZiI6MTcxODI4NDQwMiwicGF0aCI6Ii83NTk2Mjc2Mi8zMzkzMjk0MTItMzAxZjc4MjEtZTViNC00NDkzLTg2MTUtYzI0MzAyMjM5MzNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDEzMTMyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4MmZiYjhhN2FlZmIyZjVkYjg5MTBlMzhlNTJlY2QwMzI2OTcwMmUwMDU3MTA4MzM3ZjlkYzBlOGQwMmJiZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jf0GDVmJ2L8AHCbtc7SGm3ag0QaTD7LbY8rYbSKOVVw)
> 
> I'm having this error after changing `localhost` to `host.docker.internal` My versions are - ![image](https://private-user-images.githubusercontent.com/75962762/339330476-0ac61970-9041-4101-8f24-93d120f4cd30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyODQ3MDIsIm5iZiI6MTcxODI4NDQwMiwicGF0aCI6Ii83NTk2Mjc2Mi8zMzkzMzA0NzYtMGFjNjE5NzAtOTA0MS00MTAxLThmMjQtOTNkMTIwZjRjZDMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDEzMTMyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczYjg4ODg4NTc2NWVmNTVkODcyMzUwY2I3ODM2NzViZjc4N2Q1ZWE2MDc2YzhkNTFhYjIxMjk2MDEwNTk3MzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mtguv5WQetFD5BPgFNXRBhJkJLZdgxmxbDUpjY5INmw)

And are both Open WebUI and Ollama running in Docker for you?

**Comment by suman-somu** [comment]
> @suman-somu And are both Open WebUI and Ollama running in Docker for you?

yep
![image](https://github.com/open-webui/open-webui/assets/75962762/98dc8922-a2cc-475d-aa19-8abb2bfb9f87)

**Comment by silentoplayz** [comment]
> > @suman-somu And are both Open WebUI and Ollama running in Docker for you?
> 
> yep

Try `http://host.docker.internal:8000/v1`

**Comment by cediorio** [comment]
> > > @suman-somu And are both Open WebUI and Ollama running in Docker for you?
> > 
> > 
> > yep
> 
> Try `http://host.docker.internal:8000/v1` for `SearXNG Query URL`, https://docs.openwebui.com/tutorial/openedai-speech-integration

Did this work for anyone? I've had the same exact problems: host.docker.internal returns 403, while localhost gives the "Expecting value" error. Both open-webui and searxing running in unmodified docker containers, open-webui:cuda running 0.3.5.

**Comment by rwestberg** [comment]
> ![image](https://private-user-images.githubusercontent.com/75962762/339329412-301f7821-e5b4-4493-8615-c2430223933c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMzgwOTQsIm5iZiI6MTcxOTIzNzc5NCwicGF0aCI6Ii83NTk2Mjc2Mi8zMzkzMjk0MTItMzAxZjc4MjEtZTViNC00NDkzLTg2MTUtYzI0MzAyMjM5MzNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDE0MDMxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlNjRlMGFkMGUwODJmYzI2YmZhNTAzYzE0NWVkODU0NWM3NzFiY2YzZTllZDkyODczZWQ1ZTUwNGMwODJhMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LZ6BsCqfrE26cS2ccS4J6Z6hwphgKS7ZNCY0rUsMRXA)
> 
> I'm having this error after changing `localhost` to `host.docker.internal` My versions are - ![image](https://private-user-images.githubusercontent.com/75962762/339330476-0ac61970-9041-4101-8f24-93d120f4cd30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMzgwOTQsIm5iZiI6MTcxOTIzNzc5NCwicGF0aCI6Ii83NTk2Mjc2Mi8zMzkzMzA0NzYtMGFjNjE5NzAtOTA0MS00MTAxLThmMjQtOTNkMTIwZjRjZDMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDE0MDMxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhOGQ1MzMwZWUwNmMxYmFkY2YyOGYwMmI5NTExMTM2YjgwMTJhODM0ZjhlZDhiZTdmZTY2M2JhYWEyZDc5ZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.chYOmeFoVUsF2xrDsE2vqzhtRSPRYiQazwBEagG9EYQ)

Looks like the default settings for searxng is to disallow search results in json. I had to edit my settings.yml to add it:

```  
  # remove format to deny access, use lower case.
  # formats: [html, csv, json, rss]
  formats:
    - html
    - json
```

After that the 403 error went away and things seem to work!

**Comment by JasonOdinberg** [comment]
For everyone who gets an error ,you need to edit the settings.yml , given that you've installed searxng with docker, make sure to start the container and then click on it , go to files , etc/searxng/settings.yml (right click and edit file) and the part that you need to change should be around line 78 , 
``  formats:
    - html
    ``
    It is missing the -json file most of the times , so add it.
    ``
      formats:
    - html
    - json
    ``
