### ISSUE TITLE
Use currently loaded model for chat title generation

### ISSUE THREAD

**Issue by KMouratidis** [open-webui/open-webui#5299]
**Is your feature request related to a problem? Please describe.**

Yes. I have an ollama's `llama3.1:70b-instruct-q4_K_S` model imported and set as the default for my user account, as well as under `Admin>Users>Manage Models>Default Model` and `Admin>Interface>Set Task Model`. Under `Workspace`, I edit the model to set some custom parameters (e.g. `num_gpu`, `num_predict`, etc), including `Context Length=16384`. I open a new chat and send a message, the model gets loaded and generates the reply.

A few seconds later, the model gets unloaded, only to get reloaded again but with `n_ctx=2048` in order to generate the title for the chat. As a result, when it's done and I send a new message, another unload+load happens with the parameters I've set. If instead of sending a new message I edit my original or request a re-generation, then the cycle happens yet another time!

**Describe the solution you'd like**

It would be cool if the chat renaming function used the already loaded model as is, especially since it is the exact same model and the only thing that's different is the "Advanced Params" section.

**Describe alternatives you've considered**

Not sure what a *viable* alternative would be.

**Additional context**

- Version: v0.3.20
- Ollama: 0.3.10

```
# first request sent, loading model:

ollama  | time=2024-09-09T17:53:14.229Z level=INFO source=server.go:391 msg="starting llama server" cmd="/tmp/ollama349776158/runners/cuda_v12/ollama_llama_server --model /root/.ollama/models/blobs/sha256-7e1ca97e0d39109ebd4c253ce3f60fb886a7abf328f34e4c99b834874b16b9b6 --ctx-size 16384 --batch-size 512 --embedding --log-disable --n-gpu-layers 81 --threads 1 --flash-attn --no-mmap --mlock --parallel 1 --tensor-split 39,39 --port 33159"
...
ollama  | llm_load_tensors:  CUDA_Host buffer size =   563.62 MiB
ollama  | llm_load_tensors:      CUDA0 buffer size = 19142.57 MiB
ollama  | llm_load_tensors:      CUDA1 buffer size = 18764.43 MiB
ollama  | llama_new_context_with_model: n_ctx      = 16384
ollama  | llama_new_context_with_model: n_batch    = 512
ollama  | llama_new_context_with_model: n_ubatch   = 512
ollama  | llama_new_context_with_model: flash_attn = 1
ollama  | llama_new_context_with_model: freq_base  = 500000.0
ollama  | llama_new_context_with_model: freq_scale = 1
ollama  | llama_kv_cache_init:      CUDA0 KV buffer size =  2624.00 MiB
ollama  | llama_kv_cache_init:      CUDA1 KV buffer size =  2496.00 MiB
ollama  | llama_new_context_with_model: KV self size  = 5120.00 MiB, K (f16): 2560.00 MiB, V (f16): 2560.00 MiB
ollama  | llama_new_context_with_model:  CUDA_Host  output buffer size =     0.52 MiB
ollama  | llama_new_context_with_model: pipeline parallelism enabled (n_copies=4)
ollama  | llama_new_context_with_model:      CUDA0 compute buffer size =   368.01 MiB
ollama  | llama_new_context_with_model:      CUDA1 compute buffer size =   394.52 MiB
ollama  | llama_new_context_with_model:  CUDA_Host compute buffer size =   144.02 MiB
ollama  | llama_new_context_with_model: graph nodes  = 2247
ollama  | llama_new_context_with_model: graph splits = 3
ollama  | INFO [main] model loaded | tid="139687063945216" timestamp=1725904401
ollama  | time=2024-09-09T17:53:21.239Z level=INFO source=server.go:629 msg="llama runner started in 7.00 seconds"
ollama  | [GIN] 2024/09/09 - 17:53:30 | 200 | 18.169522003s |    192.168.1.54 | POST     "/api/chat"

# first request done, loading model again (notice: it's the same file)

ollama  | time=2024-09-09T17:53:32.849Z level=INFO source=sched.go:731 msg="new model will fit in available VRAM, loading" model=/root/.ollama/models/blobs/sha256-7e1ca97e0d39109ebd4c253ce3f60fb886a7abf328f34e4c99b834874b16b9b6 library=cuda parallel=1 required="41.7 GiB"
ollama  | time=2024-09-09T17:53:32.849Z level=INFO source=server.go:101 msg="system memory" total="124.9 GiB" free="109.8 GiB" free_swap="0 B"
ollama  | time=2024-09-09T17:53:32.850Z level=INFO source=memory.go:326 msg="offload to cuda" layers.requested=-1 layers.model=81 layers.offload=81 layers.split=41,40 memory.available="[23.3 GiB 23.3 GiB]" memory.gpu_overhead="0 B" memory.required.full="41.7 GiB" memory.required.partial="41.7 GiB" memory.required.kv="640.0 MiB" memory.required.allocations="[21.2 GiB 20.4 GiB]" memory.weights.total="36.8 GiB" memory.weights.repeating="36.0 GiB" memory.weights.nonrepeating="822.0 MiB" memory.graph.full="1.1 GiB" memory.graph.partial="1.1 GiB"
ollama  | time=2024-09-09T17:53:32.853Z level=INFO source=server.go:391 msg="starting llama server" cmd="/tmp/ollama349776158/runners/cuda_v12/ollama_llama_server --model /root/.ollama/models/blobs/sha256-7e1ca97e0d39109ebd4c253ce3f60fb886a7abf328f34e4c99b834874b16b9b6 --ctx-size 2048 --batch-size 512 --embedding --log-disable --n-gpu-layers 81 --flash-attn --parallel 1 --tensor-split 41,40 --port 35271"
...
ollama  | llm_load_tensors:        CPU buffer size =   563.62 MiB
ollama  | llm_load_tensors:      CUDA0 buffer size = 19142.57 MiB
ollama  | llm_load_tensors:      CUDA1 buffer size = 18764.43 MiB
ollama  | llama_new_context_with_model: n_ctx      = 2048
```

**Comment by TheTerrasque** [comment]
Came here to report the same issue. Looks like the title generation doesn't take into account advanced parameters when sending in the request, which with context size causes model reloading.

**Comment by tjbck** [comment]
Should be fixed on dev, testing wanted here!

**Comment by KMouratidis** [comment]
Tested both `dev` and `main` and can confirm my issue was fixed! Thanks!

**Comment by TheTerrasque** [comment]
I've only tested release (v0.3.28), but the problem is still there for me. Also happens with tool use, which makes things very slow.

I have the context size set via Settings -> General -> Advanced parameters though, so it applies to all models for my user.
