### ISSUE TITLE
Both Plain Text and PDF download are broken

### ISSUE THREAD

**Issue by mattcaron** [open-webui/open-webui#5737]
# Bug Report

## Installation Method

Manual install.
```
       git clone https://github.com/open-webui/open-webui.git
       cd open-webui
       npm install
       npm run build
       python3.11 -m venv venv
       source venv/bin/activate
       pip install --upgrade pip
       pip install -r backend/requirements.txt -U
```

## Environment

- **Open WebUI Version:** v0.3.30
- **Ollama (if applicable):** 0.3.12

- **Operating System:** Ubuntu 24.04
- **Browser (if applicable):** Firefox 130.0.1

**Confirmation:**

- [X] I have read and followed all the instructions provided in the README.md.
- [X] I am on the latest version of both Open WebUI and Ollama.
- [X] I have included the browser console logs.
- [X] I have included the ~~Docker container~~ logs. 
  - Not using docker, but I've included the relevant output lines from the shell.
- [X] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

I expected to be able to download PDF and text files like I can with `.json`

## Actual Behavior:

Nothing. No user feedback at all.

## Description

**Bug Summary:**

When clicking Download->Plain Text or Download->PDF, nothing happens.

## Reproduction Details

**Steps to Reproduce:**

1. Install Open-WebUI
2. Install Ollama
3. Do some chatting with your preferred model.
4. Try to download either a PDF or plain text

## Logs and Screenshots

**Browser Console Logs:**

[console-export-2024-9-26_11-0-19.txt](https://github.com/user-attachments/files/17150838/console-export-2024-9-26_11-0-19.txt)

**~~Docker Container~~ Logs:**

Not docker, from shell. First line is after selecting download of plain text. Second line is after selecting download of PDF.
```
INFO:     127.0.0.1:49256 - "GET /api/v1/chats/6654e2e0-f887-419c-bdee-a9c02c65d611/tags HTTP/1.1" 200 OK
INFO:     127.0.0.1:45094 - "POST /api/v1/utils/pdf HTTP/1.1" 422 Unprocessable Entity
```

**Comment by bgeneto** [comment]
Confirmed in dev branch also.
For text/markdown download:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'reduce')
    at _ (Menu.svelte:35:35)
    at v (Menu.svelte:43:26)
    at I.A (Menu.svelte:231:8)
    at lifecycle.js:105:8
    at Array.forEach (<anonymous>)
    at lifecycle.js:104:22
    at HTMLDivElement.<anonymous> (events.js:8:32)
    at ja (event.js:43:10)
    at HTMLDivElement.<anonymous> (event.js:48:29)
``` 
For pdf download:
```
 POST api/v1/utils/pdf 422 (Unprocessable Content)

Uncaught (in promise) TypeError: Failed to execute 'createObjectURL' on 'URL': Overload resolution failed.
    at p (Menu.svelte:59:26)
```

**Comment by tjbck** [comment]
Fixed on dev, 0.3.31 will be released shortly!

**Comment by mattcaron** [comment]
Not to be a pain, but I was a release manager for a decade... You merged to `main`, but never tagged it. ;-)

**Comment by mattcaron** [comment]
Further testing:
1. Despite commit messages to the contrary (`fix: chat pdf, txt export issue`) on `main`, these are not fixed. But, you never claimed that they were.
2. Checking `dev`, it works great. Both `txt` and `pdf` download pass tests.
