### ISSUE TITLE
Models not loading  v0.4.0 (latest)

### ISSUE THREAD

**Issue by vishnunuk** [open-webui/open-webui#7058]
## Installation Method

Docker

## Environment

- **Open WebUI Version:** v0.4.0(latest)
- **Ollama (if applicable):** 0.4.2

<img width="1918" alt="Screenshot 2024-11-20 at 6 51 56 AM" src="https://github.com/user-attachments/assets/cd7ac0d1-996a-4976-979e-4d0a196e99bc">

<img width="2032" alt="Screenshot 2024-11-20 at 6 56 26 AM" src="https://github.com/user-attachments/assets/00d89085-c8bb-484e-aef0-02f0e988bee8">

**Comment by tjbck** [comment]
Should be fixed in dev, testing wanted here!

**Comment by ashkansamadiyan** [comment]
Can i ask if you have browser cache cleared? i keep getting unhealthy container with no errors in docker logs!
i did purne the volumes and ofcourse old image! (first tried updating via compose pull)

**Comment by vishnunuk** [comment]
@tjbck 
Tested v0.4.1
Unfortunately models still not loading in https://localchat.duckdns.org/workspace/models or http://localhost:8000/workspace/models
<img width="2032" alt="Screenshot 2024-11-20 at 7 18 14 AM" src="https://github.com/user-attachments/assets/16e42c56-24a3-42e9-a536-5f503384d9f1">
<img width="1915" alt="Screenshot 2024-11-20 at 7 17 43 AM" src="https://github.com/user-attachments/assets/4ab55150-29e3-4821-910d-4c75975cdb70">

**Comment by tjbck** [comment]
@vishnunuk All of your base models are moved to Admin Settings > "Models" as mentioned in the changelog :)

**Comment by vishnunuk** [comment]
@tjbck found it in https://localchat.duckdns.org/admin/settings . Thanks

**Comment by Aloereed** [comment]
However, it is difficult to adjust the position of the model in /admin/settings.

**Comment by PHILI729** [comment]
I got the same issue, macbook, M2, have you fixed it? pls share.
