### ISSUE TITLE
enh: support for disabling rag in web search

### ISSUE THREAD

**Issue by EntropyYue** [open-webui/open-webui#9999]
The web search has become very slow due to rag, it would be great if we could turn off rag, and for cases where the context length is insufficient, we can solve it by setting a limit on the number of characters in the returned results

**Comment by juan-abia** [comment]
We should have an option to dissable RAG entirily

**Comment by nachogmd** [comment]
This should be quite straight forward, let me now @tjbck if you need someone taking this over

**Comment by tjbck** [comment]
Addressed with ca0b7217d23812ca74359f4214a066b1737c8db6 in dev!

**Comment by crockpotveggies** [comment]
@tjbck may I suggest enabling full context mode/bypass RAG by default?

**Comment by reidprichard** [comment]
Seems this option has been renamed to 'Bypass Embedding and Retrieval'. Perhaps I don't understand but it doesn't seem to be working as intended - I'm still getting the RAG template added to my prompt after a web search occurs?

**Comment by Classic298** [comment]
you are confusing settings. you need to disable file_context and citations. https://docs.openwebui.com/features/chat-conversations/prompt-caching?_highlight_phrase=KV%20Cac#prompt-caching-kv-cache-optimization

**Comment by reidprichard** [comment]
That did it, many thanks! I'm not sure how I failed to come across that part of the documentation in all my searching.
